version: "3"
services:
  backend:
    volumes:
      - ./backend/src:/usr/local/backend/src
      - ./generic:/usr/local/backend/node_modules/@checkers/generic
    build:
      target: development
    ports:
      - ${INTERNAL_BACKEND_WS_PORT}:${INTERNAL_BACKEND_WS_PORT}
    command: npm run start:dev
  client:
    volumes:
      - ./client/src:/usr/local/client/src
      - ./client/public:/usr/local/client/public
      - ./generic:/usr/local/client/node_modules/@checkers/generic
    build:
      target: development
    environment:
      - WEBPACK_DEV_SERVER_HOST=${WEBPACK_DEV_SERVER_HOST}
      - WEBPACK_DEV_SERVER_PORT=${WEBPACK_DEV_SERVER_PORT}
      - INTERNAL_BACKEND_WS_PORT=${INTERNAL_BACKEND_WS_PORT}
    ports:
      - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}
    command: npm run start:dev
