version: "3"
services:
  backend:
    volumes:
      - ./backend/src:/usr/local/backend/src
      - ./generic:/usr/local/backend/node_modules/@checkers/generic
    build:
      target: development
    command: npm run start:dev
  client:
    volumes:
      - ./client/src:/usr/local/client/src
      - ./client/public:/usr/local/client/public
      - ./generic:/usr/local/client/node_modules/@checkers/generic
    build:
      target: development
    environment:
      - DEV_BACKEND_WS_PORT=${DEV_BACKEND_WS_PORT}
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    command: npm run start:dev
